import { StyleSheet } from "react-native";
import COLORS from "../constants/colors";

const styles = StyleSheet.create({
  //css de welcome
  imgwelcome: {
    flex: 1,
    resizeMode: "cover",
  },
  container: {
    paddingHorizontal: 22,
    paddingTop: "50%",
    flexDirection: "column",
    width: "100%",
    height: "100%",
  },
  tittle: {
    fontSize: 65,
    marginBottom: "8%",
    alignSelf: "center",
    color: COLORS.white,
    fontFamily: "Roboto-Italic",
  },
  subtittle: {
    fontSize: 25,
    color: COLORS.white,
    fontFamily: "Helvetica",
    textAlign: "center",
    marginBottom: "10%",
  },
  containerTextInputs: {
    width: "100%",
    height: 50,
    borderColor: "#F1EFEF",
    backgroundColor: "#F2F2F2",
    borderWidth: 1,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 25,
    marginBottom: 20,
    shadowColor: "rgba(0, 0, 0, 0.4)",
    shadowOpacity: 0.8,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 2 },
  },
  TextInput: {
    width: "100%",
    alignItems: "center",
    fontFamily: "Roboto-LightItalic",
  },
  press: {
    flexDirection: "row",
    marginTop: 25,
    justifyContent: "center",
  },
  pressuser: {
    flexDirection: "row",
    marginTop: "auto",
    justifyContent: "center",
    marginBottom: "30%",
  },
  tx: {
    fontSize: 17,
    color: COLORS.white,
    fontFamily: "Roboto-Italic",
  },
  txc: {
    fontSize: 17,
    color: COLORS.primary,
    fontFamily: "Roboto-Italic",
    textDecorationLine: "underline",
  },
  containerInputswelcome: {
    marginBottom: "10%",
  },
  //hasta aqui
  containertittle: {
    marginTop: 30,
    marginBottom: 20,
  },
  buttontheme: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    alignSelf: "center",
  },
  buttonsettings: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "grey", // Puedes ajustar el color según tus preferencias
    width: "100%",
  },
  slider: {
    width: "80%",
    alignSelf: "center",
    marginTop: "7%",
  },
  textinput2: {
    width: "60%",
    height: 40,
    borderColor: COLORS.buttonprimary,
    borderWidth: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
  containertittle2: {
    marginTop: 30,
  },
  containerSolucion1: {
    paddingHorizontal: 22,
    marginTop: 5,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  containerexp: {
    marginTop: 20,
  },
  containeruser: {
    marginTop: "5%",
    paddingHorizontal: 22,
  },
  img: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    position: "absolute",
  },
  containerbtn: {
    paddingHorizontal: 22,
    marginTop: 24,
  },
  map: {
    width: "90%",
    height: "100%",
    borderRadius: 20,
  },
  containermap: {
    marginTop: 40,
    alignItems: "center",
    height: 250,
    marginBottom: 25,
  },
  containerinfo: {
    borderRadius: 30,
    marginTop: 15,
    marginHorizontal: 10,
    padding: 20,
    backgroundColor: "rgba(201, 214, 223, 0.5)",
  },
  containersettings: {
    borderRadius: 30,
    marginHorizontal: 10,
    padding: 20,
    backgroundColor: "rgba(201, 214, 223, 0.5)",
  },
  containerlogo: {
    marginTop: 30,
    marginBottom: 20,
    flexDirection: "row",
    marginHorizontal: 10,
    justifyContent: "center",
  },
  containerSol: {
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "center",
  },
  scroll: {
    flex: 1,
  },
  principaltittle: {
    fontSize: 23,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 5,
    marginHorizontal: 20,
    color: "black",
    //fontFamily: "Roboto-Italic",
  },
  principaltittle1: {
    fontSize: 16,
    textAlign: "center",
    marginTop: 5,
    color: "black",
  },
  centeredText: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 5,
    color: "black",
  },
  usertittle: {
    fontSize: 40,
    fontWeight: "bold",
    marginTop: 5,
    color: "black",
  },
  tittle1: {
    fontSize: 20,
    textAlign: "center",
    marginTop: 5,
    marginHorizontal: 20,
    color: "black",
    //fontFamily: "Roboto-Italic",
  },
  textmodal: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 12,
    marginTop: 13,
    color: "black",
    lineHeight: 22,
  },
  tittle2: {
    fontSize: 16,
    textAlign: "center",
    marginTop: 10,
    color: "black",
    //fontFamily: "Helvetica",
  },
  tittle3: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 12,
    marginTop: 13,
    color: "black",
  },
  tittle4: {
    fontSize: 15,
    textAlign: "center",
    marginTop: 15,
    color: "black",
    //fontFamily: "Roboto-Italic",
  },
  tittle5: {
    fontSize: 15,
    marginTop: 18,
    fontFamily: "Roboto-Italic",
    color: "black",
  },
  tittle6: {
    fontSize: 14,
    marginTop: 15,
    marginBottom: 7,
    fontFamily: "Roboto-Italic",
    color: "black",
  },
  tittle7: {
    fontSize: 14,
    marginTop: 10,
    fontFamily: "Roboto-Italic",
    color: "black",
  },
  tittle8: {
    fontSize: 20,
    textAlign: "center",
    marginTop: 25,
    marginHorizontal: 20,
    color: "black",
  },
  txtcom: {
    alignSelf: "center",
    marginTop: "3%",
    color: "black",
    fontSize: 17,
    textDecorationLine: "underline",
  },
  ref: {
    fontSize: 15,
    textAlign: "center",
    color: "grey",
  },
  textend: {
    marginTop: 150,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  textimput: {
    width: "100%",
    height: 50,
    borderColor: "#F1EFEF",
    borderWidth: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 22,
    shadowColor: "rgba(0, 0, 0, 0.4)",
    shadowOpacity: 0.8,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 2 },
    backgroundColor: "#F2F2F2",
  },
  containerInputs: {
    paddingHorizontal: 22,
    marginTop: 24,
  },
  imagedemo: {
    width: "100%",
    height: 200,
    borderRadius: 15,
    marginTop: 20,
  },
  imagedemo1: {
    width: "100%",
    height: 75,
    borderRadius: 15,
    marginTop: 20,
  },
  containerdemo: {
    marginTop: 10,
    paddingHorizontal: 22,
  },
  container1: {
    marginTop: 10,
    alignItems: "center",
    marginBottom: 10,
  },
  textodemo: {
    fontSize: 20,
    marginTop: 15,
    fontFamily: "Roboto-Italic",
    fontWeight: "bold",
    letterSpacing: 1,
    textShadowColor: "rgba(0, 0, 0, 0.4)",
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 4,
    color: "black",
  },
  textimput: {
    width: "100%",
    height: 50,
    borderColor: "#F1EFEF",
    borderWidth: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 22,
    shadowColor: "rgba(0, 0, 0, 0.4)",
    shadowOpacity: 0.8,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 2 },
    backgroundColor: "#F2F2F2",
    marginTop: 12,
  },
  textinput1: {
    width: "100%",
    height: 50,
    borderColor: "#F1EFEF",
    borderWidth: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 22,
    shadowColor: "rgba(0, 0, 0, 0.4)",
    shadowOpacity: 0.8,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 2 },
    backgroundColor: "#F2F2F2",
  },
  containerSolucion: {
    paddingHorizontal: 22,
    marginTop: 5,
  },
});
export default styles;
