import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  containertittle: {
    marginTop: 70,
    marginBottom: 20,
  },
  slider: {
  width: "80%",
  alignSelf: "center",
  marginTop: "7%",
  },
  textinput2: {
    width: "60%",
    height: 40,
    borderColor: "#F1EFEF",
    borderWidth: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
  containertittle2: {
    marginTop: 30,
  },
  containerSolucion1: {
    paddingHorizontal: 22,
    marginTop: 5,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  containerexp: {
    marginTop: 20,
  },
  containeruser: {
    marginTop: "25%",
    paddingHorizontal: 22,
  },
  img: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    position: "absolute",
  },
  containerbtn: {
    paddingHorizontal: 22,
    marginTop: 24,
  },
  map: {
    width: "90%",
    height: "100%",
    borderRadius: 20,
  },
  containermap: {
    marginTop: 40,
    alignItems: "center",
    height: 250,
    marginBottom: 25,
  },
  containerinfo: {
    borderRadius: 30,
    marginTop: 15,
    marginHorizontal: 10,
    padding: 20,
    backgroundColor: "rgba(193, 209, 240, 0.8)",
  },
  containerlogo: {
    marginTop: 70,
    marginBottom: 20,
    flexDirection: "row",
    marginHorizontal: 10,
    justifyContent: "center",
  },
  containerSol: {
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "center",
  },
  scroll: {
    flex: 1,
  },
  principaltittle: {
    fontSize: 23,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 5,
    marginHorizontal: 20,
    color: "white",
    //fontFamily: "Roboto-Italic",
  },
  principaltittle1: {
    fontSize: 16,
    textAlign: "center",
    marginTop: 5,
    color: "white",
  },
  centeredText: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 5,
    color: "black",
  },
  usertittle: {
    fontSize: 40,
    fontWeight: "bold",
    marginTop: 5,
    color: "white",
  },
  tittle1: {
    fontSize: 20,
    textAlign: "center",
    marginTop: 5,
    marginHorizontal: 20,
    color: "white",
    //fontFamily: "Roboto-Italic",
  },
  textmodal: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 12,
    marginTop: 13,
    color: "white",
    lineHeight: 22,
  },
  tittle2: {
    fontSize: 16,
    textAlign: "center",
    marginTop: 10,
    color: "black",
    //fontFamily: "Helvetica",
  },
  tittle3: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 12,
    marginTop: 13,
    color: "white",
  },
  tittle4: {
    fontSize: 15,
    textAlign: "center",
    marginTop: 15,
    color: "black",
    //fontFamily: "Roboto-Italic",
  },
  tittle5: {
    fontSize: 15,
    marginTop: 18,
    fontFamily: "Roboto-Italic",
    color: "white",
  },
  tittle6: {
    fontSize: 14,
    marginTop: 15,
    marginBottom: 7,
    fontFamily: "Roboto-Italic",
    color: "white",
  },
  tittle7: {
    fontSize: 14,
    marginTop: 10,
    fontFamily: "Roboto-Italic",
    color: "black",
  },
  tittle8: {
    fontSize: 20,
    textAlign: "center",
    marginTop: 25,
    marginHorizontal: 20,
    color: "white",
  },
  txtcom: {
    alignSelf: "center",
    marginTop: "3%",
    color: "white",
    fontSize: 17,
    textDecorationLine: "underline",
  },
  ref: {
    fontSize: 15,
    textAlign: "center",
    color: "grey",
  },
  textend: {
    marginTop: 150,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  textimput: {
    width: "100%",
    height: 50,
    borderColor: "#F1EFEF",
    borderWidth: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 22,
    shadowColor: "rgba(0, 0, 0, 0.4)",
    shadowOpacity: 0.8,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 2 },
    backgroundColor: "#F2F2F2",
  },
  containerInputs: {
    paddingHorizontal: 22,
    marginTop: 24,
  },
  imagedemo: {
    width: "100%",
    height: 200,
    borderRadius: 15,
    marginTop: 20,
  },
  imagedemo1: {
    width: "100%",
    height: 75,
    borderRadius: 15,
    marginTop: 20,
  },
  containerdemo: {
    marginTop: 30,
    paddingHorizontal: 22,
  },
  container1: {
    marginTop: 10,
    alignItems: "center",
    marginBottom: 10,
  },
  textodemo: {
    fontSize: 20,
    marginTop: 15,
    fontFamily: "Roboto-Italic",
    fontWeight: "bold",
    letterSpacing: 1,
    textShadowColor: "rgba(0, 0, 0, 0.4)",
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 4,
    color: "white",
  },
  textimput: {
    width: "100%",
    height: 50,
    borderColor: "#F1EFEF",
    borderWidth: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 22,
    shadowColor: "rgba(0, 0, 0, 0.4)",
    shadowOpacity: 0.8,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 2 },
    backgroundColor: "#F2F2F2",
    marginTop: 12,
  },
  textinput1: {
    width: "100%",
    height: 50,
    borderColor: "#F1EFEF",
    borderWidth: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 22,
    shadowColor: "rgba(0, 0, 0, 0.4)",
    shadowOpacity: 0.8,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 2 },
    backgroundColor: "#F2F2F2",
  },
  containerInputs: {
    paddingHorizontal: 22,
    marginTop: 24,
  },
  containerSolucion: {
    paddingHorizontal: 22,
    marginTop: 5,
  },
});
export default styles;
